In [3]:
evals = list()

In [204]:
import utils.common
import evaluation
import importlib
import numpy as np
import time
from models.ConstraintAutoRec import ConstraintAutoRec 
import models.NeuralLogicRec
import tensorflow as tf
import pandas as pd

importlib.reload(utils.common)
importlib.reload(evaluation)
importlib.reload(models.NeuralLogicRec)
import itertools

ml_small = utils.common.ml_small
ml_big = utils.common.movie_lens


In [205]:
ev = evaluation.Evaluation(ml_small)

In [206]:
nlr = models.NeuralLogicRec.NLR(ml_small['user'], ml_small['dimensions'], epochs=10, embedding_dim=16, batch_size=32, nr_hidden_layers=4)
# evals.append(ev.evaluate_single_thread(nlr))

In [207]:
nlr.train(utils.common.load_dataset(ml_small), ml_small['train']['records'])
evals.append(ev.evaluate_single_thread(nlr))

Epoch #0 Loss at step 19: 1.5347, time: 6.279. Train accuracy 0.360, Validation accuracy 0.856
Epoch #1 Loss at step 19: 1.5218, time: 1.884. Train accuracy 0.308, Validation accuracy 0.767
Epoch #2 Loss at step 19: 1.5006, time: 1.794. Train accuracy 0.334, Validation accuracy 0.819
Epoch #3 Loss at step 19: 1.4898, time: 1.879. Train accuracy 0.335, Validation accuracy 0.813
Epoch #4 Loss at step 19: 1.4921, time: 1.797. Train accuracy 0.347, Validation accuracy 0.842
Epoch #5 Loss at step 19: 1.4812, time: 1.886. Train accuracy 0.301, Validation accuracy 0.680
Epoch #6 Loss at step 19: 1.4711, time: 1.801. Train accuracy 0.308, Validation accuracy 0.767
Epoch #7 Loss at step 19: 1.4862, time: 1.891. Train accuracy 0.346, Validation accuracy 0.863
Epoch #8 Loss at step 19: 1.4517, time: 1.888. Train accuracy 0.503, Validation accuracy 0.805
Epoch #9 Loss at step 19: 1.4485, time: 1.809. Train accuracy 0.531, Validation accuracy 0.782
Batch nr 1 predicted
Batch nr 2 predicted


In [208]:
pd.DataFrame(evals)

accuracy  batch_size  diversity@10  diversity@5    epc@10     epc@5  \
0   0.261506          20      0.379324     0.374450  0.983260  0.982676   
1   0.249060          20      0.379273     0.383866  0.984702  0.984392   
2   0.262056          20      0.376722     0.374114  0.984894  0.984895   
3   0.245955          20      0.377471     0.374585  0.987968  0.988256   
4   0.252309          20      0.375757     0.372509  0.987330  0.987556   
5   0.254129          20      0.381217     0.380326  0.981170  0.977990   
6   0.229959          20      0.378185     0.377926  0.986357  0.986260   
7   0.245276          20      0.379347     0.379247  0.984843  0.984848   
8   0.246722          20      0.379293     0.374541  0.985977  0.985844   
9   0.238262          20      0.379342     0.375769  0.986497  0.986620   
10  0.764583          20      0.259607     0.243314  0.712231  0.685739   
11  0.762172          20      0.243882     0.225103  0.665023  0.642614   
12  0.802902          20      0.281011     0.261130  0.760215  0.743979   
13  0.756600          20      0.272045     0.254310  0.667458  0.634098   
14  0.780643          20      0.242654     0.227637  0.653187  0.615430   
15  0.787031          20      0.244649     0.227366  0.654506  0.619756   
16  0.835288          20      0.266315     0.248928  0.658647  0.626211   
17  0.766041          20      0.243327     0.232420  0.644003  0.611005   
18  0.715736          20      0.325572     0.326753  0.845301  0.827932   
19  0.798284          20      0.326121     0.329602  0.874832  0.873229   
20  0.778671          20      0.271332     0.258920  0.683413  0.654236   
21  0.787929          20      0.243976     0.231251  0.645690  0.612808   
22  0.729581          20      0.262083     0.252758  0.737926  0.722345   
23  0.761117          20      0.249158     0.242524  0.644274  0.610926   
24  0.768707          20      0.239795     0.223437  0.652130  0.627560   
25  0.747131          32      0.274804     0.259480  0.720933  0.691613   
26  0.845672          32      0.268346     0.254941  0.715476  0.684070   
27  0.757579          32      0.231946     0.227464  0.612943  0.587316   
28  0.846948          32      0.240839     0.227960  0.644701  0.619257   

       epd@5  epochs  latent_dim     map@1    map@10     map@5  \
0   0.377255      10         128  0.000000  0.000605  0.000931   
1   0.379488       4         128  0.009009  0.001184  0.001982   
2   0.376023       4         128  0.009009  0.001764  0.003153   
3   0.378574      10         128  0.004505  0.001167  0.001532   
4   0.376164      10         128  0.004505  0.001359  0.001126   
5   0.382671      10         128  0.009009  0.001959  0.003483   
6   0.375233      10         128  0.000000  0.000435  0.000300   
7   0.378133      10         128  0.004505  0.000686  0.000901   
8   0.376507      10         128  0.000000  0.000158  0.000225   
9   0.378839      10         128  0.000000  0.000165  0.000180   
10  0.316864      10         128  0.139640  0.044937  0.058241   
11  0.310763      10         128  0.171171  0.055617  0.075636   
12  0.320172      10         128  0.103604  0.035948  0.046648   
13  0.319203      10         128  0.157658  0.052586  0.073076   
14  0.312749      10         128  0.180180  0.060123  0.084655   
15  0.312924      10         128  0.175676  0.062272  0.085983   
16  0.319259      10         128  0.157658  0.051975  0.070908   
17  0.313196      10         128  0.175676  0.057845  0.081236   
18  0.346266      10         128  0.076577  0.016045  0.024377   
19  0.344061      10         128  0.058559  0.012862  0.019820   
20  0.321470      10         128  0.144144  0.051300  0.069797   
21  0.315966      10         128  0.184685  0.063459  0.084505   
22  0.321667      10         128  0.094595  0.041300  0.052962   
23  0.317063      10         128  0.148649  0.056630  0.076231   
24  0.310343      10         128  0.189189  0.064070  0.084223   
25  0.321384      10         128  0.1

In [200]:
# print(np.flip(np.argsort(nlr.predict_single_user(3))))

pp = nlr.predict(None, [0,1])
print(pp)

train = utils.common.load_dataset(ml_small).take(1)
for data in train:
    print(data)

[[0.7752004  0.6732403  0.6135279  ... 0.44160616 0.5534071  0.5490457 ]
 [0.7601892  0.6598728  0.5880598  ... 0.4484114  0.5319582  0.53132546]]
{'x': <tf.Tensor: id=7260903, shape=(10381,), dtype=bool, numpy=array([ True, False,  True, ..., False, False, False])>, 'mask': <tf.Tensor: id=7260900, shape=(10381,), dtype=bool, numpy=array([ True, False,  True, ..., False, False, False])>, 'user_id': <tf.Tensor: id=7260902, shape=(), dtype=int64, numpy=0>, 'x_test': <tf.Tensor: id=7260904, shape=(10381,), dtype=bool, numpy=array([False, False, False, ..., False, False, False])>, 'mask_test': <tf.Tensor: id=7260901, shape=(10381,), dtype=bool, numpy=array([False, False, False, ..., False, False, False])>}


In [211]:
estimations =  nlr.model([0])
np.sort(estimations['popular'])

array([0.18902892, 0.19692963, 0.19936791, ..., 0.3437705 , 0.34396967,
       0.34405974], dtype=float32)

In [100]:
num_movies = 10
num_user = 3
rated = tf.convert_to_tensor(np.arange(num_movies * num_user).reshape([num_user, num_movies]))
seen = tf.convert_to_tensor(np.arange(num_movies * num_user, num_movies * num_user * 2).reshape([num_user, num_movies]))
movies = tf.tile(tf.expand_dims(tf.convert_to_tensor(np.arange(num_movies).reshape(num_movies, 1)), axis=0), [num_user, 1, 1])
users = tf.tile(tf.expand_dims(tf.convert_to_tensor([[200], [100], [300]],dtype=tf.int64), axis=1), [1, num_movies, 1])
# print(movies)
# print(users)
res = (tf.concat([users, movies], axis=-1))
res = tf.reduce_sum(res, axis=-1)
print(res.shape)
print(res)
a = tf.reshape(res, [num_movies, num_user])
print(tf.transpose(a))


(3, 10)
tf.Tensor(
[[200 201 202 203 204 205 206 207 208 209]
 [100 101 102 103 104 105 106 107 108 109]
 [300 301 302 303 304 305 306 307 308 309]], shape=(3, 10), dtype=int64)
tf.Tensor(
[[200 203 206 209 102 105 108 301 304 307]
 [201 204 207 100 103 106 109 302 305 308]
 [202 205 208 101 104 107 300 303 306 309]], shape=(3, 10), dtype=int64)


()


InvalidArgumentError: Input to reshape is a tensor with 1 values, but the requested shape has 30 [Op:Reshape]

In [87]:
user_cross = tf.convert_to_tensor([x for x in itertools.permutations(users.numpy(), 2)])
print(user_cross)
rated_cross = tf.convert_to_tensor([tf.stack([rated[x[0]], rated[x[1]]], axis=0) for x in itertools.permutations(range(len(users.numpy())), 2)])
# print(rated_cross)

tf.Tensor(
[[20 10]
 [20  5]
 [20  0]
 [20 40]
 [10 20]
 [10  5]
 [10  0]
 [10 40]
 [ 5 20]
 [ 5 10]
 [ 5  0]
 [ 5 40]
 [ 0 20]
 [ 0 10]
 [ 0  5]
 [ 0 40]
 [40 20]
 [40 10]
 [40  5]
 [40  0]], shape=(20, 2), dtype=int32)


InvalidArgumentError: slice index 3 of dimension 0 out of bounds. [Op:StridedSlice] name: strided_slice/

In [88]:
len(user_cross)

20

In [89]:
user_emb = tf.expand_dims(tf.nn.embedding_lookup(nlr.model.user_embedding, user_cross), axis=2)
print(user_emb[:, 0])
user_embedd = tf.tile(user_emb, [1, 1, num_movies, 1])
expanded_embedd = tf.reshape(nlr.model.item_embedding, [1, 1, num_movies, 24])
item_embedd = tf.tile(expanded_embedd, [len(user_cross), 2, 1, 1])
print(item_embed.shape)
print(user_embedd.shape)
inp = tf.concat([user_embedd, item_embedd], axis=-1)

tf.Tensor(
[[[ 0.47242978 -0.7581886   0.6176951  -0.5861519   0.3641987
    0.10563103  0.61831975 -0.37575603]]

 [[ 0.47242978 -0.7581886   0.6176951  -0.5861519   0.3641987
    0.10563103  0.61831975 -0.37575603]]

 [[ 0.47242978 -0.7581886   0.6176951  -0.5861519   0.3641987
    0.10563103  0.61831975 -0.37575603]]

 [[ 0.47242978 -0.7581886   0.6176951  -0.5861519   0.3641987
    0.10563103  0.61831975 -0.37575603]]

 [[ 0.32968965  1.3128943   0.4282597  -1.8893449  -1.0829191
   -1.2234583   0.99611586  0.7264877 ]]

 [[ 0.32968965  1.3128943   0.4282597  -1.8893449  -1.0829191
   -1.2234583   0.99611586  0.7264877 ]]

 [[ 0.32968965  1.3128943   0.4282597  -1.8893449  -1.0829191
   -1.2234583   0.99611586  0.7264877 ]]

 [[ 0.32968965  1.3128943   0.4282597  -1.8893449  -1.0829191
   -1.2234583   0.99611586  0.7264877 ]]

 [[ 0.6136244   1.5436143   2.036422    1.5196469   0.08901728
   -0.90769035 -1.6418009  -0.3131709 ]]

 [[ 0.6136244   1.5436143   2.036422    1.5196469   

InvalidArgumentError: Input to reshape is a tensor with 83048 values, but the requested shape has 240 [Op:Reshape]

In [90]:
result = tf.squeeze(nlr.model.likes_estimator(inp))

NameError: name 'inp' is not defined

In [84]:
num_movies = 5
users = tf.convert_to_tensor([1, 10, 100])
embed_user = tf.expand_dims(users, axis=1)
users_1 = tf.tile(tf.expand_dims(embed_user, axis=1), [1, len(users), 1])
users_2 = tf.tile(tf.expand_dims(embed_user, axis=0), [len(users),1, 1])
# print(embed_user)
# embed_user = tf.tile(embed_user, [1, num_movies, 1])
# expanded_embedd = tf.expand_dims(nlr.model.item_embedding[0:num_movies], axis=0)
# embed_item = tf.tile(expanded_embedd, [len(users), 1, 1])
sim_input = tf.reduce_sum(tf.concat([users_1, users_2], axis=-1), axis=-1)
print(sim_input)

tf.Tensor(
[[  2  11 101]
 [ 11  20 110]
 [101 110 200]], shape=(3, 3), dtype=int32)


In [99]:
multi_ratings = tf.tile(tf.expand_dims(rated, axis=0), [3, 1, 1])

In [13]:
a = tf.convert_to_tensor(10)
# b = tf.expand_dims(tf.convert_to_tensor(20), axis=0)
# c = tf.convert_to_tensor([1,2,3,4])
len(a.shape) == 0

True

In [117]:
a = np.array([1,5,3,0], dtype=float)
b = np.array([0,2,3,0], dtype=float)
mask = np.where(b)
mask

(array([1, 2]),)

In [118]:
a[mask] / b[mask]

array([2.5, 1. ])