In [184]:

import utils.common
import evaluation
import importlib
import numpy as np
import time
from models.ConstraintAutoRec import ConstraintAutoRec 
import models.NeuralLogicRec
import tensorflow as tf
importlib.reload(utils.common)
importlib.reload(evaluation)
importlib.reload(models.NeuralLogicRec)

ml_small = utils.common.ml_small

ev = evaluation.Evaluation(ml_small)

In [185]:
nlr = models.NeuralLogicRec.NLR(ml_small['user'], ml_small['dimensions'], epochs=1, embedding_dim =16, batch_size=1200)

In [186]:
for i in range(16):
    nlr.train(utils.common.load_dataset(ml_small), ml_small['train']['records'])
    if i % 3 == 0:
        print(ev.evaluate(nlr))

Epoch #0 Loss at step 150: -0.7621, time: 16.390
Batch nr 1 predicted
waiting for queue
processing results
Evaluating NeuralLogicRec |============================================================>| 100.0% 
{'accuracy': 0.7657318741450069, 'precision': 0.8401515151515152, 'recall': 0.8939943571140669, 'map@1': 0.0, 'map@5': 0.0, 'map@10': 0.00017740429505135386, 'diversity@5': 0.36739639648057176, 'diversity@10': 0.3597071330029012, 'epc@5': 0.9889630940375962, 'epc@10': 0.9852763009762958, 'epd@5': 0.377995229968082, 'name': 'NeuralLogicRec', 'latent_dim': 128, 'epochs': 1, 'batch_size': 1200}
Epoch #0 Loss at step 150: -3.0551, time: 24.577
Epoch #0 Loss at step 150: -4.6955, time: 23.992
Epoch #0 Loss at step 150: -6.2466, time: 23.907
Batch nr 1 predicted
waiting for queue
processing results
Evaluating NeuralLogicRec |============================================================>| 100.0% 
{'accuracy': 0.746922024623803, 'precision': 0.8388478007006618, 'recall': 0.8686013704151552, 'm

In [183]:
# print(np.flip(np.sort(nlr.predict_single_user(0))))
# print(nlr.predict_single_user(1))
# nlr.model(np.array(1), np.array(1))
user = 0
nr_items = 300
items = np.arange(nr_items)
user = np.repeat(user, nr_items)
predictions = nlr.model(user, items)
# print(np.argsort(predictions['rec']))
rec = models.NeuralLogicRec.map_inference(nlr.model, predictions, 1e-7)['rec']
print(np.flip(np.argsort(rec.numpy())))

[257 151 216 117 299  25 265 246 222 211 210 159 119  50 207 173 115 143
 155  11  98  92  96  95  94 100 101  93  99  97 138  91  90  89 103  88
  87  86  85  84  83  82  81  80  79  78 102 108 104 130 124 125 126 127
 128 129 131 105 132 133 134 135 139 136 123 122 121 120 118 140 116 114
 113 112 111 110  77 141 137 107 106 109  73  76  37  20  21  22  23  24
  26  27  28  29  30  31  32  33  34  35  19  18  17   7   1   2   3   4
   5   6   8  16   9  10  12  13  14  15  36  38  75  39  59  60  61  62
  63  64  65  66  67  68  69  70  71  72  74  58  57  56  46  40  41  42
  43  44  45  47  55  48  49  51  52  53  54 142 149 144 252 245 247 248
 249 250 251 253 243 254 255 256 258 259 260 244 242 262 233 227 228 229
 230 231 232 234 241 235 236 237 238 239 240 261 263 225 290 284 285 286
 287 288 289 291 282 292 293 294 295 296 297 283 281 264 272 266 267 268
 269 270 271 273 280 274 275 276 277 278 279 226 224 145 174 167 168 169
 170 171 172 175 165 176 177 178 179 180 181 166 16

In [39]:
ev.evaluate(nlr)

Batch nr 1 predicted
waiting for queue
processing results
Evaluating NeuralLogicRec |============================================================>| 100.0% 


{'accuracy': 0.3751709986320109,
 'precision': 0.7961956521739131,
 'recall': 0.3542926239419589,
 'map@1': 0.0,
 'map@5': 0.0005602240896358543,
 'map@10': 0.00028011204481792715,
 'diversity@5': 0.38642315238836494,
 'diversity@10': 0.3854676574970965,
 'epc@5': 0.9917035977133284,
 'epc@10': 0.9912749935746786,
 'epd@5': 0.38612166561005457,
 'name': 'NeuralLogicRec',
 'latent_dim': 128,
 'epochs': 1,
 'batch_size': 1200}

In [23]:
model = models.ConstraintAutoRec.ConstraintAutoRec(ml_small['dimensions'], epochs=10, novelty_weight=0.1, diversity_weight=0.1, latent_dim=64)
model.train(utils.common.load_dataset(ml_small), ml_small['train']['records'])

Epoch 1/10
19/19 [==============================] - 8s 436ms/step - loss: 0.2566 - accuracy: 0.0000e+00
Epoch 2/10
19/19 [==============================] - 0s 13ms/step - loss: 0.1744 - accuracy: 0.0128
Epoch 3/10
19/19 [==============================] - 0s 14ms/step - loss: 0.1639 - accuracy: 0.0411
Epoch 4/10
19/19 [==============================] - 0s 14ms/step - loss: 0.1483 - accuracy: 0.0263
Epoch 5/10
19/19 [==============================] - 0s 14ms/step - loss: 0.1424 - accuracy: 0.0190
Epoch 6/10
19/19 [==============================] - 0s 13ms/step - loss: 0.1410 - accuracy: 0.0173
Epoch 7/10
19/19 [==============================] - 0s 14ms/step - loss: 0.1322 - accuracy: 0.0260
Epoch 8/10
19/19 [==============================] - 0s 15ms/step - loss: 0.1257 - accuracy: 0.0181
Epoch 9/10
19/19 [==============================] - 0s 16ms/step - loss: 0.1170 - accuracy: 0.0033
Epoch 10/10
19/19 [==============================] - 0s 15ms/step - loss: 0.1127 - accuracy: 0.0016


In [24]:
ev.evaluate(model)

Batch nr 1 predicted
waiting for queue
processing results
Evaluating ConstraintAutoRec |============================================================>| 100.0% 


{'accuracy': 0.6822845417236663,
 'precision': 0.8947100712105799,
 'recall': 0.7089883111648528,
 'map@1': 0.12605042016806722,
 'map@5': 0.05232492997198879,
 'map@10': 0.0429851504093701,
 'diversity@5': 0.23787031282623874,
 'diversity@10': 0.2646920640131162,
 'epc@5': 0.7503029009116576,
 'epc@10': 0.7542414115926078,
 'epd@5': 0.3190622687929619,
 'name': 'ConstraintAutoRec',
 'dimensions': 10379,
 'latent_dims': 64,
 'accuracy_weight': 1.0,
 'novelty_weight': 0.1,
 'diversity_weight': 0.1,
 'epochs': 10,
 'batch_size': 32,
 'optimizer': 'adam'}

In [12]:
ev.evaluate(nlr)

Batch nr 1 predicted
waiting for queue
processing results
Evaluating NeuralLogicRec |============================================================>| 100.0% 


{'accuracy': 0.1515047879616963,
 'precision': 0.0,
 'recall': 0.0,
 'map@1': 0.0,
 'map@5': 0.0,
 'map@10': 0.00030345471521942105,
 'diversity@5': 0.35353541499577024,
 'diversity@10': 0.34548889740582156,
 'epc@5': 0.9922690114451876,
 'epc@10': 0.9906619756357248,
 'epd@5': 0.3830725399040539,
 'name': 'NeuralLogicRec',
 'latent_dim': 128,
 'epochs': 50,
 'batch_size': 1000}

In [25]:
import numpy as np
import tensorflow as tf
import pandas as pd
import os

In [259]:
np.flip(np.argsort(nlr.predict_single_user(80)))

array([[2804, 3923, 5677, ..., 1019, 1335, 7248]])

In [270]:
nlr.model.user_embedding[0]

<tf.Tensor: id=14283369, shape=(8,), dtype=float32, numpy=
array([-0.25685114,  1.1030787 , -0.83440006,  1.078066  ,  0.05426935,
       -0.895161  ,  1.4823135 , -0.9063508 ], dtype=float32)>

In [86]:
a = tf.Variable(initial_value=tf.random.normal([1]))
b = tf.Variable(initial_value=tf.random.normal([1]))
tf.stack([a,b],axis=0)

<tf.Tensor: id=82112920, shape=(2,), dtype=float32, numpy=array([0.8852266, 1.1255649], dtype=float32)>

In [79]:
tf.reduce_max(a, axis=[1])

<tf.Tensor: id=8026786, shape=(3,), dtype=float32, numpy=array([ 3.1626284 , -0.2083571 ,  0.41710454], dtype=float32)>

In [106]:
def cross_2args(X,Y):
    if X.doms == [] and Y.doms == []:
        result = tf.concat([X,Y],axis=-1)
        result.doms = []
        return result,[X,Y]
    X_Y = set(X.doms) - set(Y.doms)
    Y_X = set(Y.doms) - set(X.doms)
    eX = X
    eX_doms = [x for x in X.doms]
    for y in Y_X:
        eX = tf.expand_dims(eX,0)
        eX_doms = [y] + eX_doms
    eY = Y
    eY_doms = [y for y in Y.doms]
    for x in X_Y:
        eY = tf.expand_dims(eY,-2)
        eY_doms.append(x)
    perm_eY = []
    for y in eY_doms:
        perm_eY.append(eX_doms.index(y))
    eY = tf.transpose(eY,perm=perm_eY + [len(perm_eY)])
    mult_eX = [1]*(len(eX_doms)+1)
    mult_eY = [1]*(len(eY_doms)+1)
    for i in range(len(mult_eX)-1):
        mult_eX[i] = tf.maximum(1,tf.math.floordiv(tf.shape(eY)[i],tf.shape(eX)[i]))
        mult_eY[i] = tf.maximum(1,tf.math.floordiv(tf.shape(eX)[i],tf.shape(eY)[i]))
    result1 = tf.tile(eX,mult_eX)
    result2 = tf.tile(eY,mult_eY)
    result = tf.concat([result1,result2],axis=-1)
    result1.doms = eX_doms
    result2.doms = eX_doms
    result.doms = eX_doms
    return result,[result1,result2]

a.doms = ["a"]
b.doms = ["b"]
result, _ = cross_2args(a,b )
r_and = tf.reduce_mean(result, axis=2, keepdims=True)
print(a)
print(b)
print(result)
print(r_and)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[ 3.1626284 ],
       [-0.2083571 ],
       [ 0.41710454]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[-0.15450539],
       [ 2.0219426 ],
       [-0.45979235]], dtype=float32)>
tf.Tensor(
[[[ 3.1626284  -0.15450539]
  [-0.2083571  -0.15450539]
  [ 0.41710454 -0.15450539]]

 [[ 3.1626284   2.0219426 ]
  [-0.2083571   2.0219426 ]
  [ 0.41710454  2.0219426 ]]

 [[ 3.1626284  -0.45979235]
  [-0.2083571  -0.45979235]
  [ 0.41710454 -0.45979235]]], shape=(3, 3, 2), dtype=float32)
tf.Tensor(
[[[ 1.5040615 ]
  [-0.18143123]
  [ 0.13129959]]

 [[ 2.5922856 ]
  [ 0.90679276]
  [ 1.2195235 ]]

 [[ 1.351418  ]
  [-0.33407474]
  [-0.0213439 ]]], shape=(3, 3, 1), dtype=float32)


In [115]:
vars = (a,b )
ax = [result.doms.index(var.doms[0]) for var in vars]

In [116]:
tf.reduce_mean(r_and, ax)

<tf.Tensor: id=8027635, shape=(1,), dtype=float32, numpy=array([0.7965035], dtype=float32)>